### ISSUE TITLE
Inverter CAN broadcast configuration

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu#94]
### Description
We only want some of the information which the inverter broadcasts. Broadcasting of information which we don't need should be disabled to reduce traffic on the CAN bus.

### Specification
- [x] Work out how to set which information is broadcast (see datasheet).
- [x] Create parameters in configuration header which can be set to enable/disable each broadcast message. 
- [ ] Send message to inverter with required configuration on initialisation.

### Additional context
[Cascadia Motion CAN Protocol](https://app.box.com/s/vf9259qlaadhzxqiqrt5cco8xpsn84hk/file/27334613044)

**Comment by t-bre** [comment]
@hashyaha I've constructed the bytes which need to be sent to configure broadcasting of CAN messages. Should this be set via CAN with `pm100_eeprom_write_blocking()`? There are four bytes of data which need to be sent (page 19 of datasheet, both upper words), but at the moment this function only transmits 2 bytes of data.

**Comment by hashyaha** [comment]
I think there might be discrepancy in Page 19 because in pg 44 there are two EEPROM address corresponding with CAN broadcast Hi word (237) and Lo word (148). This matches the description of parameter message in pg 38 which has 2 data bytes only.
![Screenshot 2022-05-13 150411](https://user-images.githubusercontent.com/70197006/168300905-2f341f83-305d-43bc-af98-bd6a83169715.png)

 In this case I think it may be sufficient to write to Lo word, as it is not recommended to change the default Hi word (0xFFFF).
